[
  [
    '{href:"https://mik.prod.platform.michaels.com/12-pc.-prismacolor-premier%C2%AE-colored-pencil-set/ia-12-prismacolor-premier",status:"error"}',
  ],
  [
    '{href:"https://mik.prod.platform.michaels.com/3pk-pigma-micron-pen-sets/ia-pigma-micron-3pk",status:"error"}',
  ],
  [
    '{href:"https://mik.prod.platform.michaels.com/3pk-pigma-micron-pen-sets/ia-pigma-micron-3pk",status:"error"}',
  ],
  [
    '{href:"https://mik.prod.platform.michaels.com/12-pc.-sharpie-permanent-marker-sets/ia-12pc-sharpie-sets",status:"error"}',
  ],
  [
    '{href:"https://mik.prod.platform.michaels.com/craft-smart-craft-paint-16ct-value-sets/ia-craftsmart-16ct-value-sets",status:"error"}',
  ],
  [
    '{href:"https://mik.prod.platform.michaels.com/craft-smart-craft-paint-16ct-value-sets/ia-craftsmart-16ct-value-sets",status:"error"}',
  ],
  [
    '{href:"https://mik.prod.platform.michaels.com/12-pc.-prismacolor-premier%C2%AE-colored-pencil-set/ia-12-prismacolor-premier",status:"error"}',
  ],
  [
    '{href:"https://mik.prod.platform.michaels.com/12-pc.-sharpie-permanent-marker-sets/ia-12pc-sharpie-sets",status:"error"}',
  ],
  [
    '{href:"https://mik.prod.platform.michaels.com/kids-back-to-school-supplies/back-to-school-storage/bts-storage?pmid=onsale",status:"error"}',
  ],
  [
    '{href:"https://mik.prod.platform.michaels.com/kids-back-to-school-supplies/back-to-school-storage/bts-storage?pmid=onsale",status:"error"}',
  ],
  [
    '{href:"https://mik.prod.platform.michaels.com/kids-back-to-school-supplies/back-to-school-storage/bts-storage?pmid=onsale",status:"error"}',
  ],
  ['{href:"https://merchant.sgiftcard.com/chrome/michaels",status:"error"}'],
  ['{href:"https://www.instagram.com/michaelsstores",status:"error"}'],
];
