// console.log(
//   new Set([
//     "/",
//     "/accessibility",
//     "/affiliate-program",
//     "/black-friday",
//     "/boredom-busters",
//     "/camp-creatology",
//     "/cart",
//     "/coupon-policy-and-price-guarantee",
//     "/coupons",
//     "/curbside-pickup",
//     "/customer-care",
//     "/cyber-monday",
//     "/design-library",
//     "/diversity",
//     "/download-app",
//     "/guest-history/browsing-history",
//     "/labor-day",
//     "/lowest-prices-of-the-season",
//     "/marketplace",
//     "/michaels-gives-back",
//     "/michaels-pro",
//     "/military-discount",
//     "/presidents-day",
//     "/product-policy/ca-product-policy",
//     "/product-recalls",
//     "/red-white-blue-sale",
//     "/return-policy",
//     "/rewards",
//     "/rewards/rewards-faq",
//     "/rewards/terms",
//     "/senior-discount",
//     "/shipping-policy",
//     "/signin",
//     "/signup",
//     "/site-map",
//     "/store-locator",
//     "/tax-exempt",
//     "/teacher-discount",
//     "/terms-and-conditions",
//     "/track-my-order",
//     "/weekly-ad",
//     "/welcome-ac-moore",
//     "/yarn-pattern-library",
//     "/your-privacy-rights",
//     "/classes",
//     "/projects",
//     "/infusible-ink",
//     "/projects/yarn",
//     "/shipping-policy/ca-shipping-policy",
//     "/tech101",
//     "/design-library",
//     "/labor-day",
//     "/lowest-prices-of-the-season",
//     "/yarn-pattern-library",
//     "/return-policy/ca-return-policy",
//     "/coupon-policy/ca-coupon-policy",
//     "/product-recalls/ca-recall",
//     "/teachers",
//     "/privacyrights",
//     "/jewelry-reseller",
//     "/marketing-coupon",
//     "/red-white-blue-sale",
//     "/small-business",
//     "/presidents-day",
//     "/teachergiveaway",
//     "/maker-academy",
//     "/welcome-ac-moore",
//     "/covid-19-response",
//     "/michaels-pro",
//     "/ups-service",
//     "/site-map",
//     "/value-info",
//     "/download-app",
//     "/diversity",
//     "/michaels-gives-back",
//     "/shipping-policy",
//     "/return-policy",
//     "/product-recalls",
//     "/terms-and-conditions",
//     "/your-privacy-rights",
//     "/product-policy/ca-product-policy",
//     "/weekly-ad",
//     "/michaels-rating-and-review-sweepstakes/ratings-reviews-tc",
//     "/waiting-room",
//     "/jobs",
//     "/covid-19-response",
//     "/ups-service",
//     "/site-map",
//     "/value-info",
//     "/download-app",
//     "/michaels-gives-back",
//     "/diversity",
//     "/shipping-policy",
//     "/return-policy",
//     "/product-recalls",
//     "/terms-and-conditions",
//     "/your-privacy-rights",
//     "/product-policy/ca-product-policy",
//     "/weekly-ad",
//     "/michaels-rating-and-review-sweepstakes/ratings-reviews-tc",
//     "/terms&conditions",
//     "/return-policy/ca-return-policy",
//     "/product-recalls/ca-recall",
//     "/shipping-policy/ca-shipping-policy",
//     "/coupon-policy/ca-coupon-policy",
//     "/privacyrights",
//     "/waiting-room",
//     "/teachergiveaway",
//     "/jewelry-reseller",
//     "/small-business",
//     "/maker-academy",
//     "/red-white-blue-sale",
//     "/presidents-day",
//     "/lowest-prices-of-the-season",
//     "/projects/yarn",
//     "/yarn-pattern-library",
//     "/labor-day",
//     "/tech101",
//     "/teachers",
//     "/marketing-coupon",
//     "/infusible-ink",
//     "/welcome-ac-moore",
//     "/luck",

//     /balloon-inflation
//     /sustainability
//     /sustainability/environmental
//     /sustainability/governance
//     /sustainability/social
//     /tool-rental
//   ])
// );

// const aa = [
//   "/accessibility",
//   "/affiliate-program",
//   "/balloon-inflation",
//   "/black-friday",
//   "/boredom-busters",
//   "/camp-creatology",
//   "/coupon-policy-and-price-guarantee",
//   "/coupon-policy/ca-coupon-policy",
//   "/covid-19-response",
//   "/cyber-monday",
//   "/design-library",
//   "/diversity",
//   "/download-app",
//   "/infusible-ink",
//   "/jobs",
//   "/labor-day",
//   "/lowest-prices-of-the-season",
//   "/luck",
//   "/maker-academy",
//   "/marketing-coupon",
//   "/michaels-gives-back",
//   "/michaels-pro",
//   "/michaels-rating-and-review-sweepstakes/ratings-reviews-tc",
//   "/presidents-day",
//   "/privacyrights",
//   "/product-policy/ca-product-policy",
//   "/product-recalls",
//   "/product-recalls/ca-recall",
//   "/projects/yarn",
//   "/red-white-blue-sale",
//   "/return-policy",
//   "/return-policy/ca-return-policy",
//   "/shipping-policy",
//   "/shipping-policy/ca-shipping-policy",
//   "/site-map",
//   "/small-business",
//   "/sustainability",
//   "/sustainability/environmental",
//   "/sustainability/governance",
//   "/sustainability/social",
//   "/teachergiveaway",
//   "/teachers",
//   "/tech101",
//   "/terms-and-conditions",
//   "/terms&conditions",
//   "/tool-rental",
//   "/ups-service",
//   "/value-info",
//   "/weekly-ad",
//   "/welcome-ac-moore",
//   "/yarn-pattern-library",
//   "/your-privacy-rights",
// ];
// const vv = Array.from(
//   new Set([
//     "/",
//     "/accessibility",
//     "/affiliate-program",
//     "/black-friday",
//     "/boredom-busters",
//     "/camp-creatology",
//     "/cart",
//     "/coupon-policy-and-price-guarantee",
//     "/coupons",
//     "/curbside-pickup",
//     "/customer-care",
//     "/cyber-monday",
//     "/design-library",
//     "/diversity",
//     "/download-app",
//     "/guest-history/browsing-history",
//     "/labor-day",
//     "/lowest-prices-of-the-season",
//     "/marketplace",
//     "/michaels-gives-back",
//     "/michaels-pro",
//     "/military-discount",
//     "/presidents-day",
//     "/product-policy/ca-product-policy",
//     "/product-recalls",
//     "/red-white-blue-sale",
//     "/return-policy",
//     "/rewards",
//     "/rewards/rewards-faq",
//     "/rewards/terms",
//     "/senior-discount",
//     "/shipping-policy",
//     "/signin",
//     "/signup",
//     "/site-map",
//     "/store-locator",
//     "/tax-exempt",
//     "/teacher-discount",
//     "/terms-and-conditions",
//     "/track-my-order",
//     "/weekly-ad",
//     "/welcome-ac-moore",
//     "/yarn-pattern-library",
//     "/your-privacy-rights",
//     "/classes",
//     "/projects",
//     "/infusible-ink",
//     "/projects/yarn",
//     "/shipping-policy/ca-shipping-policy",
//     "/tech101",
//     "/design-library",
//     "/labor-day",
//     "/lowest-prices-of-the-season",
//     "/yarn-pattern-library",
//     "/return-policy/ca-return-policy",
//     "/coupon-policy/ca-coupon-policy",
//     "/product-recalls/ca-recall",
//     "/teachers",
//     "/privacyrights",
//     "/jewelry-reseller",
//     "/marketing-coupon",
//     "/red-white-blue-sale",
//     "/small-business",
//     "/presidents-day",
//     "/teachergiveaway",
//     "/maker-academy",
//     "/welcome-ac-moore",
//     "/covid-19-response",
//     "/michaels-pro",
//     "/ups-service",
//     "/site-map",
//     "/value-info",
//     "/download-app",
//     "/diversity",
//     "/michaels-gives-back",
//     "/shipping-policy",
//     "/return-policy",
//     "/product-recalls",
//     "/terms-and-conditions",
//     "/your-privacy-rights",
//     "/product-policy/ca-product-policy",
//     "/weekly-ad",
//     "/withoutHeader/accessibility",
//     "/withoutHeader/affiliate-program",
//     "/withoutHeader/coupon-policy-and-price-guarantee",
//     "/withoutHeader/covid-19-response",
//     "/withoutHeader/diversity",
//     "/withoutHeader/product-policy/ca-product-policy",
//     "/withoutHeader/product-recalls",
//     "/withoutHeader/return-policy",
//     "/withoutHeader/shipping-policy",
//     "/withoutHeader/terms-and-conditions",
//     "/withoutHeader/your-privacy-rights",
//     "/michaels-rating-and-review-sweepstakes/ratings-reviews-tc",
//     "/waiting-room",
//     "/jobs",
//     "/covid-19-response",
//     "/ups-service",
//     "/site-map",
//     "/value-info",
//     "/download-app",
//     "/michaels-gives-back",
//     "/diversity",
//     "/shipping-policy",
//     "/return-policy",
//     "/product-recalls",
//     "/terms-and-conditions",
//     "/your-privacy-rights",
//     "/product-policy/ca-product-policy",
//     "/weekly-ad",
//     "/michaels-rating-and-review-sweepstakes/ratings-reviews-tc",
//     "/terms&conditions",
//     "/return-policy/ca-return-policy",
//     "/product-recalls/ca-recall",
//     "/shipping-policy/ca-shipping-policy",
//     "/coupon-policy/ca-coupon-policy",
//     "/privacyrights",
//     "/waiting-room",
//     "/teachergiveaway",
//     "/jewelry-reseller",
//     "/small-business",
//     "/maker-academy",
//     "/red-white-blue-sale",
//     "/presidents-day",
//     "/lowest-prices-of-the-season",
//     "/projects/yarn",
//     "/yarn-pattern-library",
//     "/labor-day",
//     "/tech101",
//     "/teachers",
//     "/marketing-coupon",
//     "/infusible-ink",
//     "/welcome-ac-moore",
//     "/luck",
//   ])
// );
// vv.forEach((item) => {
//   if (!aa.includes(item)) {
//     aa.push(item);
//   }
// });
// console.log(aa);

const result = [
  "/accessibility",
  "/affiliate-program",
  "/balloon-inflation",
  "/black-friday",
  "/boredom-busters",
  "/camp-creatology",
  "/coupon-policy-and-price-guarantee",
  "/coupon-policy/ca-coupon-policy",
  "/covid-19-response",
  "/cyber-monday",
  "/design-library",
  "/diversity",
  "/download-app",
  "/infusible-ink",
  "/jobs",
  "/labor-day",
  "/lowest-prices-of-the-season",
  "/luck",
  "/maker-academy",
  "/marketing-coupon",
  "/michaels-gives-back",
  "/michaels-pro",
  "/michaels-rating-and-review-sweepstakes/ratings-reviews-tc",
  "/presidents-day",
  "/privacyrights",
  "/product-policy/ca-product-policy",
  "/product-recalls",
  "/product-recalls/ca-recall",
  "/projects/yarn",
  "/red-white-blue-sale",
  "/return-policy",
  "/return-policy/ca-return-policy",
  "/shipping-policy",
  "/shipping-policy/ca-shipping-policy",
  "/site-map",
  "/small-business",
  "/sustainability",
  "/sustainability/environmental",
  "/sustainability/governance",
  "/sustainability/social",
  "/teachergiveaway",
  "/teachers",
  "/tech101",
  "/terms-and-conditions",
  "/terms&conditions",
  "/tool-rental",
  "/ups-service",
  "/value-info",
  "/weekly-ad",
  "/welcome-ac-moore",
  "/yarn-pattern-library",
  "/your-privacy-rights",
  "/",
  "/cart",
  "/coupons",
  "/curbside-pickup",
  "/customer-care",
  "/guest-history/browsing-history",
  "/marketplace",
  "/military-discount",
  "/rewards",
  "/rewards/rewards-faq",
  "/rewards/terms",
  "/senior-discount",
  "/signin",
  "/signup",
  "/store-locator",
  "/tax-exempt",
  "/teacher-discount",
  "/track-my-order",
  "/classes",
  "/projects",
  "/withoutHeader/accessibility",
  "/withoutHeader/affiliate-program",
  "/withoutHeader/coupon-policy-and-price-guarantee",
  "/withoutHeader/covid-19-response",
  "/withoutHeader/diversity",
  "/withoutHeader/product-policy/ca-product-policy",
  "/withoutHeader/product-recalls",
  "/withoutHeader/return-policy",
  "/withoutHeader/shipping-policy",
  "/withoutHeader/terms-and-conditions",
  "/withoutHeader/your-privacy-rights",
  "/waiting-room",
];
console.log(result.length)
